# Generated by Django 5.2.4 on 2026-02-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0003_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
    ]
