# Generated by Django 5.2.4 on 2026-02-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0004_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
