# Generated by Django 5.2.4 on 2026-03-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0009_recipe_rejection_reason_recipe_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time_to_cook',
            field=models.PositiveIntegerField(blank=True, help_text='Time to cook in minutes', null=True),
        ),
    ]
