# Generated by Django 5.2.4 on 2026-03-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0010_recipe_time_to_cook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='time_to_cook',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Dairy', 'Dairy'), ('Meat', 'Meat'), ('Poultry', 'Poultry'), ('Seafood', 'Seafood'), ('Spices', 'Spices & Herbs'), ('Baking', 'Baking & Grains'), ('Condiments', 'Condiments & Sauces'), ('Oils', 'Oils & Fats'), ('Nuts', 'Nuts & Seeds'), ('Beverages', 'Beverages'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
