# Generated by Django 5.2.4 on 2026-03-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0011_remove_recipe_time_to_cook_ingredient_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='category',
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings_unit',
            field=models.CharField(default='persons', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='number_of_servings',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
