# Generated by Django 5.2.4 on 2026-03-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0012_remove_ingredient_category_recipe_servings_unit_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='group_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('recipe', 'name', 'group_name')},
        ),
    ]
