# Generated by Django 5.2.4 on 2026-04-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0014_alter_ingredient_unique_together_ingredientgroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='group',
        ),
        migrations.DeleteModel(
            name='IngredientGroup',
        ),
    ]
