# Generated by Django 5.2.4 on 2026-03-01 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0009_recipe_rejection_reason_recipe_status'),
        ('User', '0002_notification_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='Recipe.recipe'),
        ),
    ]
